---

- name: Print the variables
  debug:
    msg: My name is {{ myname }} works with {{ mycomp }}
     
- name: More ways to print the variables
  debug: msg="My name is {{ myname }} works with {{ mycomp }}"

     
- name: Some more ways to print the variables
  debug: 
    var: myname
    verbosity: 0 
  
...         

      
