---

- name: ensure apache is at the latest version
  yum:
    name: httpd
    state: latest

- name: write the apache config file
  template:
    src: /home/tester/httpd.j2
    dest: /tmp/httpd.conf
  notify:
    - restart apache

- name: ensure apache is running
  service:
    name: httpd
    state: started

...
