---

- name: Install common software requirements
  yum: name={{ item }} state=latest
  with_items:
    - git
    - htop
    - vim

- name: Print the list elements 
  command: echo {{ item }}
  loop: [ 0, 2, 4, 6, 8, 10 ]
  when: item > 5

...
